### ISSUE TITLE
bluez-alsa codec support

### ISSUE THREAD

**Issue by marcaurelkiefer** [spietika/meta-rpi-bt-dac#3]
it would be nice to include codec support for other (better sounding) codecs than sbc.

bluez-alsa already seems to support them, but they need to be enabled explicitly via configure script, eg. through: 

--enable-aac

see: https://github.com/Arkq/bluez-alsa/wiki/Installation-from-source

AptX and ldac only seem to support encoding, but thats not useful for our scenario, since we need decoding as a sink as far as I understand.

Maybe a bump to a newer version of bluez-alsa is required...

**Comment by spietika** [comment]
Adding the support for AAC was actually quite straightforward. I added the configuration option you mentioned, and also ported fdk-aac recipe from meta-openembeeded master branch. Now when I pair the device to my phone it shows "HD Audio". Thanks for the suggestion!
